### ISSUE TITLE
Question : Systrace Stages in record window

### ISSUE THREAD

**Issue by theapache64** [Grigory-Rylov/android-methods-profiler#101]
![image](https://github.com/Grigory-Rylov/android-methods-profiler/assets/9678279/7a2f634d-0abb-4af3-9cfc-0567e5c79191)

I don't understand what's the purpose of this option? Could you care to explain little bit?

**Comment by Grigory-Rylov** [comment]
On one of the previous projects, the developers actively monitored the app startup time. To do this, metrics are sent corresponding to different stages of the application start: for example, Application.onCreate(), Activity.onCreate, FirstFrameDrawn, FirstDataShown, and so on. Usually, the drawdown of a particular metric occurred due to the fact that some method was called earlier than it needed to be. For the convenience of tracking such cases, I introduced the concept of Stage: the time interval from one metric to another. It turns out that all calls during the start can be attributed to one or another Stage. Yamp has functionality that allows you to see an early method call that should have been called at a later stage. Such a tool helped to find regression during the new release. so Stages could be defined in 2 ways: choose a chain of methods that will correspond to the beginning of the Stage. This approach has a disadvantage: a method that is too fast may not get into trace due to sampling. The second way to determine the Stage is to label the Systrace labels with the desired prefix.
